// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdrrmbkbxyqmvxktaozl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkcnJtYmtieHlxbXZ4a3Rhb3psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTIxNjksImV4cCI6MjA3MTk2ODE2OX0.SnCcjkAqjudpGU9KRL5cVYh4gfFt2AIhD7as45ICQcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});